version: "3"

services:
  redis:
    image: redis:latest
    command: redis-server --requirepass example
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      REDIS_PASSWORD: example
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: example
    depends_on:
      - redis

volumes:
  redis_data:

